package org.klozevitz.services.interfaces.updateProcessors.callbackQueryUpdateProcessors;

import org.klozevitz.messageProcessors.CallbackQueryUpdateProcessor;

public interface WaitingForEmailConfirmationStateCQUP extends CallbackQueryUpdateProcessor {
}
