package org.klozevitz.services.interfaces.updateProcessors.callbackQueryUpdateProcessors;

import org.klozevitz.messageProcessors.legacy.CallbackQueryUpdateProcessor;

public interface WaitingForDepartmentTelegramUserIdStateCQUP extends CallbackQueryUpdateProcessor {
}
