create table admin_t
(
    id int8 generated by default as identity,
    primary key (id)
);

create table app_user_t
(
    id int8 generated by default as identity,
    first_login_date timestamp,
    telegram_user_id int8 not null,
    username varchar(255),
    admin_id int8,
    company_id int8,
    department_id int8,
    employee_id int8,
    primary key (id)
);

create table category_t
(
    id int8 generated by default as identity,
    name varchar(255),
    department_id int8,
    primary key (id)
);

create table company_t
(
    id int8 generated by default as identity,
    current_view varchar(255),
    email varchar(255),
    name varchar(255),
    state varchar(255) not null,
    primary key (id)
);

create table department_t
(
    id int8 generated by default as identity,
    state varchar(255),
    company_id int8,
    primary key (id)
);

create table employee_t
(
    id int8 generated by default as identity,
    state varchar(255),
    department_id int8,
    primary key (id)
);

create table ingredient_t
(
    id int8 generated by default as identity,
    name varchar(255),
    units varchar(255),
    weight float8,
    item_id int8,
    primary key (id)
);

create table item_t
(
    id int8 generated by default as identity,
    name varchar(255),
    units varchar(255),
    weight float8,
    category_id int8,
    primary key (id)
);