package org.klozevitz.services.interfaces.messageProcessors.callbackQueryMessageProcessors;

import org.klozevitz.messageProcessors.CallbackQueryMessageProcessor;

public interface WaitingForEmailConfirmationStateCQMP extends CallbackQueryMessageProcessor {
}
