alter table if exists app_user_t drop constraint if exists FKi9lowk2137j2cv493n3j59res;
alter table if exists app_user_t drop constraint if exists FK6y56y067lqa6uul3l4yhile0p;
alter table if exists app_user_t drop constraint if exists FK4ec45sbeeokvvncjhs3gaiiw4;
alter table if exists app_user_t drop constraint if exists FKmlola79fgwn6tfv4n86sfutq5;
alter table if exists category_t drop constraint if exists FK87qjm4etpb5lqcmefeku1h5s1;
alter table if exists category_t drop constraint if exists FKtbscvyp0m43if6vaksuyc29lb;
alter table if exists department_t drop constraint if exists FKc9o3ace2u8nc54i0w8f1k2u6x;
alter table if exists employee_t drop constraint if exists FK9pkilhik6q7nxbl7nqwsilaut;
alter table if exists ingredient_t drop constraint if exists FKbt1tcqqpwxtoekx394tuet6do;
alter table if exists item_t drop constraint if exists FK7e375auelwueew9w2mmkit5jn;
alter table if exists item_t drop constraint if exists FK3f3pdlvwaovhlk09eg6mveej3;

drop table if exists admin_t cascade;
drop table if exists app_user_t cascade;
drop table if exists category_t cascade;
drop table if exists company_t cascade;
drop table if exists department_t cascade;
drop table if exists employee_t cascade;
drop table if exists excel_document_t cascade;
drop table if exists ingredient_t cascade;
drop table if exists item_t cascade;
drop table if exists test_question_t cascade;

create table admin_t
(
    id int8 generated by default as identity,
    primary key (id)
);
create table app_user_t
(
    id               int8 generated by default as identity,
    first_login_date timestamp,
    telegram_user_id int8 not null,
    username         varchar(255),
    admin_id         int8,
    company_id       int8,
    department_id    int8,
    employee_id      int8,
    primary key (id)
);
create table category_t
(
    id            int8 generated by default as identity,
    name          varchar(255),
    department_id int8,
    excel_doc_id  int8,
    primary key (id)
);
create table company_t
(
    id           int8 generated by default as identity,
    current_view varchar(255),
    email        varchar(255),
    name         varchar(255),
    state        varchar(255),
    primary key (id)
);
create table department_t
(
    id           int8 generated by default as identity,
    current_view varchar(255),
    state        varchar(255),
    company_id   int8,
    primary key (id)
);
create table employee_t
(
    id            int8 generated by default as identity,
    current_view  varchar(255),
    state         varchar(255),
    department_id int8,
    primary key (id)
);
create table excel_document_t
(
    id               int8 generated by default as identity,
    as_byte_array    bytea,
    file_size        int8,
    mime_type        varchar(255),
    name             varchar(255),
    telegram_file_id varchar(255),
    primary key (id)
);
create table ingredient_t
(
    id      int8 generated by default as identity,
    name    varchar(255),
    units   varchar(255),
    weight  float8,
    item_id int8,
    primary key (id)
);
create table item_t
(
    id               int8 generated by default as identity,
    name             varchar(255),
    units            varchar(255),
    weight           float8,
    category_id      int8,
    test_question_id int8,
    primary key (id)
);
create table test_question_t
(
    id       int8 generated by default as identity,
    variant1 varchar(255),
    variant2 varchar(255),
    variant3 varchar(255),
    variant4 varchar(255),
    primary key (id)
);

alter table if exists app_user_t add constraint UK_p67ono8k3fpip2cvwvs1i71p4 unique (telegram_user_id);
alter table if exists app_user_t add constraint FKi9lowk2137j2cv493n3j59res foreign key (admin_id) references admin_t;
alter table if exists app_user_t add constraint FK6y56y067lqa6uul3l4yhile0p foreign key (company_id) references company_t;
alter table if exists app_user_t add constraint FK4ec45sbeeokvvncjhs3gaiiw4 foreign key (department_id) references department_t;
alter table if exists app_user_t add constraint FKmlola79fgwn6tfv4n86sfutq5 foreign key (employee_id) references employee_t;
alter table if exists category_t add constraint FK87qjm4etpb5lqcmefeku1h5s1 foreign key (department_id) references department_t;
alter table if exists category_t add constraint FKtbscvyp0m43if6vaksuyc29lb foreign key (excel_doc_id) references excel_document_t;
alter table if exists department_t add constraint FKc9o3ace2u8nc54i0w8f1k2u6x foreign key (company_id) references company_t;
alter table if exists employee_t add constraint FK9pkilhik6q7nxbl7nqwsilaut foreign key (department_id) references department_t;
alter table if exists ingredient_t add constraint FKbt1tcqqpwxtoekx394tuet6do foreign key (item_id) references item_t;
alter table if exists item_t add constraint FK7e375auelwueew9w2mmkit5jn foreign key (category_id) references category_t;
alter table if exists item_t add constraint FK3f3pdlvwaovhlk09eg6mveej3 foreign key (test_question_id) references test_question_t;