package org.klozevitz.enitites.appUsers.enums.views;

public enum DepartmentView {
    NULL_DEPARTMENT_STATE_ERROR_VIEW,
    WRONG_APP_USER_ROLE_ERROR_VIEW,
    NOT_REGISTERED_DEPARTMENT_ERROR_VIEW,
    WELCOME_VIEW,
    EMPLOYEES_MANAGEMENT_VIEW,
    MATERIAL_MANAGEMENT_VIEW,
    PROFILE_MANAGEMENT_VIEW
}
