create table admin_t
(
    id int8 generated by default as identity,
    primary key (id)
);

create table app_user_t
(
    id int8 generated by default as identity,
    first_login_date timestamp,
    telegram_user_id int8 not null,
    username varchar(255),
    admin_id int8,
    company_id int8,
    department_id int8,
    employee_id int8,
    primary key (id)
);

create table category_t
(
    id int8 generated by default as identity,
    name varchar(255),
    department_id int8,
    excel_doc_id int8,
    primary key (id)
);

create table company_t
(
    id int8 generated by default as identity,
    current_view varchar(255),
    email varchar(255),
    name varchar(255),
    state varchar(255),
    primary key (id)
);

create table department_t
(
    id int8 generated by default as identity,
    current_view varchar(255),
    state varchar(255),
    company_id int8,
    primary key (id)
);

create table employee_t
(
    id int8 generated by default as identity,
    current_test jsonb,
    current_view varchar(255),
    name varchar(255),
    state varchar(255),
    department_id int8,
    primary key (id)
);

create table excel_document_t
(
    id int8 generated by default as identity,
    as_byte_array bytea,
    file_size int8,
    mime_type varchar(255),
    name varchar(255),
    telegram_file_id varchar(255),
    primary key (id)
);

create table ingredient_t
(
    id int8 generated by default as identity,
    name varchar(255),
    units varchar(255),
    weight float8,
    item_id int8,
    primary key (id)
);

create table item_t
(
    id int8 generated by default as identity,
    name varchar(255),
    units varchar(255),
    weight float8,
    category_id int8,
    question_id int8,
    primary key (id)
);

create table message_sent_t
(
    id int8 generated by default as identity,
    answer jsonb,
    message_id int4,
    app_user_id int8,
    primary key (id)
);

create table test_question_t
(
    id int8 generated by default as identity,
    variant1 varchar(255),
    variant2 varchar(255),
    variant3 varchar(255),
    variant4 varchar(255),
    item_id int8,
    primary key (id)
);

create table test_result_t
(
    id int8 generated by default as identity,
    result int4,
    employee_id int8,
    test_id int8,
    primary key (id)
);

create table test_t
(
    id int8 generated by default as identity,
    correct_answers_number int4,
    current_item_id int4 not null,
    menu jsonb,
    primary key (id)
);